### ISSUE TITLE
Token de acesso

### ISSUE THREAD

**Issue by arthurjardim2** [samuelrochaoliveira/FiscalBr#1]
Olá fui rodar os testes para ver como funciona a Lib e precisa de um token, como consigo?

![image](https://user-images.githubusercontent.com/10833029/28386826-384ae12a-6ca3-11e7-8572-8d346c82dda5.png)

**Comment by samuelrochaoliveira** [comment]
Fala Arthur, na paz?
O token é gerado no site do [IBPT](https://deolhonoimposto.ibpt.org.br/). Crie o login, cadastre alguma empresa e depois é só consumir a API.

Abraços.
